# Generated by Django 6.0.7 on 2026-07-23 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='level',
            field=models.CharField(choices=[('info', 'Инфо'), ('warning', 'Предупреждение'), ('critical', 'Важно')], default='info', max_length=10),
        ),
    ]
