# Generated by Django 6.0.7 on 2026-08-13 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_notification_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('director', 'Директор (обзор и решения по тендерам)'), ('manager', 'Менеджер (тендеры/договоры)'), ('technologist', 'Технолог (изделия, BOM, техкарты, нормы)'), ('accountant', 'Бухгалтер (финансы)'), ('warehouse', 'Кладовщик'), ('worker', 'Сотрудник цеха'), ('viewer', 'Только просмотр')], default='viewer', max_length=20),
        ),
    ]
