# Generated by Django 5.2.17 on 2026-08-31 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, verbose_name='Ключ доступа')),
                ('level', models.CharField(choices=[('none', 'Нет доступа'), ('read', 'Только просмотр'), ('write', 'Просмотр и изменение')], max_length=10, verbose_name='Уровень')),
                ('note', models.CharField(blank=True, help_text='Зачем выдано — чтобы через полгода было понятно', max_length=255, verbose_name='Основание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Точечное право',
                'verbose_name_plural': 'Точечные права',
                'ordering': ['user', 'key'],
                'unique_together': {('user', 'key')},
            },
        ),
    ]
