# Generated by Django 5.2.17 on 2026-09-14 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_useraccess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('director', 'Директор (видит всё, решает по тендерам)'), ('manager', 'Менеджер (тендеры, договоры)'), ('technologist', 'Технолог цеха (заказы, этапы, бригады)'), ('accountant', 'Бухгалтер (оплаты, расходы, финансы)'), ('warehouse', 'Кладовщик (склад)'), ('worker', 'Сотрудник цеха (записи этапов)'), ('viewer', 'Только просмотр')], default='viewer', max_length=20),
        ),
    ]
