# Generated by Django 5.2.17 on 2026-09-01 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_alter_material_min_stock_alter_materialbatch_qty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialbatch',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='warehouse.supplier'),
        ),
    ]
