# Generated by Django 5.2.17 on 2026-09-01 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_alter_materialbatch_supplier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='materialbatch',
            options={'ordering': ['-received_at', '-id']},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['name']},
        ),
    ]
