# Generated by Django 5.2.17 on 2026-09-14 09:13

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_contract_comment_contract_contract_no_and_more'),
        ('warehouse', '0004_alter_material_options_alter_materialbatch_options_and_more'),
        ('workshop', '0002_stagetemplate_alter_sewingjob_size_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='work_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_movements', to='workshop.workorder', verbose_name='Заказ цеха'),
        ),
        migrations.AlterField(
            model_name='material',
            name='min_stock',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Мин. остаток'),
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='material',
            name='sku',
            field=models.CharField(blank=True, max_length=64, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='material',
            name='unit',
            field=models.CharField(default='м', max_length=20, verbose_name='Ед. изм.'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='reason',
            field=models.CharField(choices=[('purchase', 'Приход партии'), ('production', 'Выдача в цех'), ('adjustment', 'Корректировка / инвентаризация'), ('return', 'Возврат')], max_length=20),
        ),
        migrations.CreateModel(
            name='GoodsMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('in', 'Приход'), ('out', 'Отгрузка')], max_length=3)),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата')),
                ('product', models.CharField(max_length=150, verbose_name='Изделие')),
                ('size', models.CharField(blank=True, max_length=40, verbose_name='Размер')),
                ('qty', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Штук')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_movements', to='contracts.contract')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_movements', to='workshop.workorder')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
