# Generated by Django 5.2.17 on 2026-09-14 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_convert_goods'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='material',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='supplier',
        ),
        migrations.DeleteModel(
            name='FinishedGoodsMovement',
        ),
        migrations.DeleteModel(
            name='PurchaseOrder',
        ),
    ]
