# Generated by Django 5.2.17 on 2026-09-14 08:31

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Статья')),
                ('position', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Проект')),
                ('status', models.CharField(choices=[('active', 'В работе'), ('done', 'Завершён')], default='active', max_length=10)),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['status', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AdminExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сумма')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('month', models.DateField(blank=True, help_text='Первое число месяца', null=True, verbose_name='Месяц')),
                ('source', models.CharField(choices=[('manual', 'Вручную'), ('excel', 'Из Excel')], default='manual', max_length=10)),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='projects.admincategory')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сумма')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('kind', models.CharField(choices=[('delivery', 'Доставка'), ('travel', 'Командировки'), ('samples', 'Образцы и лекала'), ('fabric', 'Ткань и материалы'), ('accessories', 'Фурнитура и шевроны'), ('sewing', 'Пошив, крой, вышивка'), ('packaging', 'Упаковка'), ('purchase', 'Закуп товара'), ('percent', 'Проценты и сертификаты'), ('legal', 'Пени, суды, документы'), ('other', 'Прочее')], default='other', max_length=20, verbose_name='Вид')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('source', models.CharField(choices=[('manual', 'Вручную'), ('excel', 'Из Excel')], default='manual', max_length=10)),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='projects.project')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сумма')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('source', models.CharField(choices=[('manual', 'Вручную'), ('excel', 'Из Excel')], default='manual', max_length=10)),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incomes', to='projects.project')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
    ]
