# Generated by Django 6.0.7 on 2026-07-23 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='importance',
            field=models.CharField(choices=[('normal', 'Обычный'), ('important', 'Важный')], default='normal', max_length=10),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('negotiation', 'Согласование'), ('in_progress', 'В работе'), ('closed', 'Закрыт'), ('cancelled', 'Отменён')], default='new', max_length=20),
        ),
    ]
