# Generated by Django 5.2.17 on 2026-09-01 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_alter_contract_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractfile',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['name']},
        ),
    ]
