# Generated by Django 5.2.17 on 2026-09-14 08:31

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_alter_contractfile_options_alter_customer_options'),
        ('projects', '0001_initial'),
        ('tenders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарии'),
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_no',
            field=models.CharField(blank=True, max_length=100, verbose_name='Номер договора'),
        ),
        migrations.AddField(
            model_name='contract',
            name='costs_note',
            field=models.CharField(blank=True, max_length=100, verbose_name='Затраты'),
        ),
        migrations.AddField(
            model_name='contract',
            name='delivery_place',
            field=models.CharField(blank=True, max_length=255, verbose_name='Место поставки'),
        ),
        migrations.AddField(
            model_name='contract',
            name='delivery_terms',
            field=models.TextField(blank=True, verbose_name='Срок поставки'),
        ),
        migrations.AddField(
            model_name='contract',
            name='investor',
            field=models.CharField(blank=True, max_length=150, verbose_name='Инвестор'),
        ),
        migrations.AddField(
            model_name='contract',
            name='note',
            field=models.TextField(blank=True, verbose_name='Коментарий'),
        ),
        migrations.AddField(
            model_name='contract',
            name='own_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='tenders.owncompany', verbose_name='С какой фирмы'),
        ),
        migrations.AddField(
            model_name='contract',
            name='payment_note',
            field=models.CharField(blank=True, max_length=100, verbose_name='Оплата'),
        ),
        migrations.AddField(
            model_name='contract',
            name='phone',
            field=models.CharField(blank=True, max_length=255, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='contract',
            name='planned_execution',
            field=models.CharField(blank=True, max_length=100, verbose_name='Планируемый срок исполнения'),
        ),
        migrations.AddField(
            model_name='contract',
            name='platform',
            field=models.CharField(blank=True, max_length=100, verbose_name='Площадка'),
        ),
        migrations.AddField(
            model_name='contract',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='contract',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='projects.project', verbose_name='Проект'),
        ),
        migrations.AddField(
            model_name='contract',
            name='purchase_no',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Номер закупки'),
        ),
        migrations.AddField(
            model_name='contract',
            name='qty',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Кол-во'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='number',
            field=models.CharField(max_length=100, verbose_name='Номер'),
        ),
    ]
