# Generated by Django 5.2.17 on 2026-09-14 09:13

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_alter_contractfile_options_alter_customer_options'),
        ('tenders', '0002_remove_tender_product_alter_tender_cost_per_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарии'),
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_no',
            field=models.CharField(blank=True, max_length=100, verbose_name='Номер договора'),
        ),
        migrations.AddField(
            model_name='contract',
            name='costs_note',
            field=models.CharField(blank=True, max_length=100, verbose_name='Затраты'),
        ),
        migrations.AddField(
            model_name='contract',
            name='delivery_place',
            field=models.CharField(blank=True, max_length=255, verbose_name='Место поставки'),
        ),
        migrations.AddField(
            model_name='contract',
            name='delivery_terms',
            field=models.TextField(blank=True, verbose_name='Срок поставки'),
        ),
        migrations.AddField(
            model_name='contract',
            name='investor',
            field=models.CharField(blank=True, max_length=150, verbose_name='Инвестор'),
        ),
        migrations.AddField(
            model_name='contract',
            name='note',
            field=models.TextField(blank=True, verbose_name='Коментарий'),
        ),
        migrations.AddField(
            model_name='contract',
            name='own_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='tenders.owncompany', verbose_name='С какой фирмы'),
        ),
        migrations.AddField(
            model_name='contract',
            name='payment_note',
            field=models.CharField(blank=True, max_length=100, verbose_name='Оплата'),
        ),
        migrations.AddField(
            model_name='contract',
            name='phone',
            field=models.CharField(blank=True, max_length=255, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='contract',
            name='planned_execution',
            field=models.CharField(blank=True, max_length=100, verbose_name='Планируемый срок исполнения'),
        ),
        migrations.AddField(
            model_name='contract',
            name='platform',
            field=models.CharField(blank=True, max_length=100, verbose_name='Площадка'),
        ),
        migrations.AddField(
            model_name='contract',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='contract',
            name='purchase_no',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Номер закупки'),
        ),
        migrations.AddField(
            model_name='contract',
            name='qty',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Кол-во'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Сумма без НДС'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Срок исполнения'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='number',
            field=models.CharField(max_length=100, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='signed_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата подписания'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='specification',
            field=models.TextField(blank=True, verbose_name='Техническая спецификация'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Предмет закупки'),
        ),
        migrations.CreateModel(
            name='ContractExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.localdate, null=True, verbose_name='Дата')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сумма')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('kind', models.CharField(choices=[('delivery', 'Доставка'), ('travel', 'Командировки'), ('samples', 'Образцы и лекала'), ('fabric', 'Ткань и материалы'), ('accessories', 'Фурнитура и шевроны'), ('sewing', 'Пошив, крой, вышивка'), ('packaging', 'Упаковка'), ('purchase', 'Закуп товара'), ('percent', 'Проценты и сертификаты'), ('legal', 'Пени, суды, документы'), ('other', 'Прочее')], default='other', max_length=20, verbose_name='Вид')),
                ('source', models.CharField(choices=[('manual', 'Вручную'), ('excel', 'Из Excel')], default='manual', max_length=10)),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='contracts.contract')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ContractPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.localdate, null=True, verbose_name='Дата')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сумма')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('source', models.CharField(choices=[('manual', 'Вручную'), ('excel', 'Из Excel')], default='manual', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='contracts.contract')),
            ],
            options={
                'ordering': [models.OrderBy(models.F('date'), descending=True, nulls_last=True), '-id'],
            },
        ),
    ]
