# Generated by Django 5.2.17 on 2026-09-14 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_convert_money'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentScheduleItem',
        ),
    ]
