# Generated by Django 5.2.17 on 2026-09-14 03:57

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0004_alter_contractfile_options_alter_customer_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brigade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leader', models.CharField(max_length=100, verbose_name='Бригадир')),
                ('people', models.PositiveSmallIntegerField(default=0, verbose_name='Людей с бригадиром')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Примечание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Работает')),
            ],
            options={
                'ordering': ['-is_active', 'leader'],
            },
        ),
        migrations.CreateModel(
            name='SewingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Выдано, шт')),
                ('started', models.DateField(default=django.utils.timezone.localdate, verbose_name='Выдано')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brigade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='workshop.brigade')),
            ],
            options={
                'ordering': ['-started', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SewingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата')),
                ('ready', models.DecimalField(decimal_places=3, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))], verbose_name='Готовность')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='workshop.sewingjob')),
            ],
            options={
                'ordering': ['date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=150, verbose_name='Изделие')),
                ('client', models.CharField(blank=True, help_text='Если договора нет: «Павлодар», «частный заказ»', max_length=200, verbose_name='Для кого')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Срок')),
                ('sewing_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Расценка пошива, ₸/шт')),
                ('status', models.CharField(choices=[('in_work', 'В работе'), ('done', 'Сдан')], default='in_work', max_length=10)),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='contracts.contract')),
            ],
            options={
                'ordering': ['-status', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=40, verbose_name='Размер')),
                ('planned', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='План, шт')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='workshop.workorder')),
            ],
            options={
                'ordering': ['position', 'id'],
                'unique_together': {('order', 'size')},
            },
        ),
        migrations.AddField(
            model_name='sewingjob',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sewing', to='workshop.worksize'),
        ),
        migrations.CreateModel(
            name='PackEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата')),
                ('qty', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Упаковано, шт')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packs', to='workshop.worksize')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='EmbroideryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата')),
                ('qty', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Вышито, шт')),
                ('kind', models.CharField(blank=True, help_text='полный, карман…', max_length=60, verbose_name='Вид')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='embroidery', to='workshop.worksize')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CutEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата')),
                ('qty', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Скроено, шт')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuts', to='workshop.worksize')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CutMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=60, verbose_name='Материал')),
                ('meters', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Расход, м')),
                ('cut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='workshop.cutentry')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('cut', 'material')},
            },
        ),
    ]
