# Generated by Django 5.2.17 on 2026-09-14 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='projects.project'),
        ),
    ]
