# Generated by Django 5.2.17 on 2026-09-14 09:13

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='Этап')),
                ('kind', models.CharField(choices=[('cut', 'Крой — штуки и расход ткани'), ('count', 'Штуки по размерам'), ('sewing', 'Пошив — партии бригад, готовность по дням')], default='count', max_length=10, verbose_name='Вид листа')),
                ('extra_label', models.CharField(blank=True, help_text='Например «Вид» у вышивки: полный, карман. Пусто — колонки нет', max_length=40, verbose_name='Дополнительная колонка')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Включать в новые заказы')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.AlterField(
            model_name='sewingjob',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='workshop.worksize'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='client',
            field=models.CharField(blank=True, help_text='Если договора нет: «частный заказ»', max_length=200, verbose_name='Для кого'),
        ),
        migrations.CreateModel(
            name='WorkOrderStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='workshop.workorder')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_stages', to='workshop.stagetemplate')),
            ],
            options={
                'ordering': ['template__position', 'template_id'],
                'unique_together': {('order', 'template')},
            },
        ),
        migrations.CreateModel(
            name='StageEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата')),
                ('qty', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Штук')),
                ('extra', models.CharField(blank=True, max_length=60, verbose_name='Доп. колонка')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='workshop.worksize')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='workshop.workorderstage')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='sewingjob',
            name='stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='workshop.workorderstage'),
        ),
        migrations.CreateModel(
            name='EntryMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=60, verbose_name='Материал')),
                ('meters', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Расход, м')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='workshop.stageentry')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('entry', 'material')},
            },
        ),
    ]
