# Generated by Django 5.2.17 on 2026-09-16 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0005_normalize_sizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='sewing_rate',
        ),
    ]
