# Generated by Django 5.2.17 on 2026-09-16 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0006_remove_workorder_sewing_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='stageentry',
            name='brigade',
            field=models.ForeignKey(blank=True, help_text='Бригада или человек из справочника бригад', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='workshop.brigade', verbose_name='Кто делал'),
        ),
    ]
