# Generated by Django 6.0.7 on 2026-08-13 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0002_alter_comment_importance_alter_contract_status'),
        ('production', '0004_stagetemplate_product_norm_hours_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('bin_iin', models.CharField(blank=True, max_length=12, verbose_name='БИН')),
                ('note', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Своё юрлицо',
                'verbose_name_plural': 'Свои юрлица',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Площадка')),
                ('url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Площадка',
                'verbose_name_plural': 'Площадки закупок',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_no', models.CharField(blank=True, max_length=100, verbose_name='Номер закупки')),
                ('lot_no', models.CharField(blank=True, max_length=100, verbose_name='Номер лота')),
                ('customer_name', models.CharField(max_length=255, verbose_name='Организация-заказчик')),
                ('item_name', models.CharField(max_length=255, verbose_name='Наименование товара')),
                ('qty', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Цена заказчика за ед., ₸')),
                ('plan_price', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Наша плановая цена за ед., ₸')),
                ('cost_per_unit', models.DecimalField(decimal_places=2, default=0, help_text='Можно подтянуть из каталога кнопкой', max_digits=14, verbose_name='Себестоимость за ед., ₸')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Дата окончания приёма заявок')),
                ('deadline_time', models.TimeField(blank=True, null=True, verbose_name='Время окончания')),
                ('delivery_days', models.CharField(blank=True, max_length=100, verbose_name='Срок поставки после договора')),
                ('samples_required', models.CharField(blank=True, max_length=255, verbose_name='Предоставление образцов')),
                ('status', models.CharField(choices=[('planned', 'В плане (изучаем)'), ('submitted', 'Заявка подана'), ('rejected', 'Заявка отклонена'), ('won', 'Выиграли'), ('lost', 'Проиграли'), ('declined', 'Отбой (не участвуем)')], default='planned', max_length=20, verbose_name='Статус')),
                ('submitted_at', models.DateField(blank=True, null=True, verbose_name='Заявка подана')),
                ('decision', models.CharField(blank=True, max_length=255, verbose_name='Итоговое решение')),
                ('docs_url', models.URLField(blank=True, verbose_name='Ссылка на документацию')),
                ('note', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tender', to='contracts.contract', verbose_name='Созданный договор')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenders', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
                ('own_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenders.owncompany', verbose_name='От какой фирмы подаём')),
                ('platform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenders', to='tenders.platform', verbose_name='Площадка')),
                ('product', models.ForeignKey(blank=True, help_text='Связь с каталогом — чтобы взять себестоимость по BOM', null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.product', verbose_name='Изделие из каталога')),
            ],
            options={
                'verbose_name': 'Тендер / лот',
                'verbose_name_plural': 'Тендеры (план закупок)',
                'ordering': ['-created_at'],
            },
        ),
    ]
