# Generated by Django 5.2.17 on 2026-09-14 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tender',
            name='product',
        ),
        migrations.AlterField(
            model_name='tender',
            name='cost_per_unit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Оценка: ткань, фурнитура, пошив, доставка', max_digits=14, verbose_name='Себестоимость за ед., ₸'),
        ),
    ]
