# Generated by Django 6.0.6 on 2026-07-06 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('kind', models.CharField(choices=[('fixed', 'Тұрақты (постоянные)'), ('variable', 'Өзгермелі (переменные)')], default='variable', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CashEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('in', 'Кіріс (поступление)'), ('out', 'Шығыс (расход)')], max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('date', models.DateField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_entries', to='contracts.contract')),
                ('category', models.ForeignKey(blank=True, help_text='Для расходов: материал, зарплата, аренда...', null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.expensecategory')),
            ],
            options={
                'verbose_name_plural': 'Cash entries',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
