# Generated by Django 6.0.7 on 2026-07-23 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashentry',
            name='direction',
            field=models.CharField(choices=[('in', 'Поступление'), ('out', 'Расход')], max_length=3),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='kind',
            field=models.CharField(choices=[('fixed', 'Постоянные'), ('variable', 'Переменные')], default='variable', max_length=10),
        ),
    ]
