# Generated by Django 6.0.7 on 2026-08-13 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_cashentry_direction_alter_expensecategory_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('per_hour', 'На нормо-час (точнее)'), ('per_unit', 'На единицу продукции (проще)')], default='per_hour', max_length=10, verbose_name='Метод распределения')),
                ('planned_monthly_units', models.PositiveIntegerField(default=1000, help_text='Для метода «на единицу»', verbose_name='Плановый выпуск, шт/мес')),
                ('planned_monthly_hours', models.DecimalField(decimal_places=2, default=1000, help_text='Для метода «на нормо-час»', max_digits=10, verbose_name='Плановый фонд рабочего времени, ч/мес')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Настройки себестоимости',
                'verbose_name_plural': 'Настройки себестоимости',
            },
        ),
        migrations.CreateModel(
            name='FixedCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование')),
                ('monthly_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Сумма в месяц, ₸')),
                ('is_active', models.BooleanField(default=True, verbose_name='Действует')),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.expensecategory')),
            ],
            options={
                'verbose_name': 'Постоянный расход',
                'verbose_name_plural': 'Постоянные расходы',
                'ordering': ['-is_active', 'name'],
            },
        ),
    ]
