# Generated by Django 5.2.17 on 2026-09-01 03:44

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_costsettings_fixedcost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashentry',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='costsettings',
            name='planned_monthly_hours',
            field=models.DecimalField(decimal_places=2, default=1000, help_text='Для метода «на нормо-час»', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Плановый фонд рабочего времени, ч/мес'),
        ),
        migrations.AlterField(
            model_name='costsettings',
            name='planned_monthly_units',
            field=models.PositiveIntegerField(default=1000, help_text='Для метода «на единицу»', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Плановый выпуск, шт/мес'),
        ),
        migrations.AlterField(
            model_name='fixedcost',
            name='monthly_amount',
            field=models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Сумма в месяц, ₸'),
        ),
    ]
