# Generated by Django 5.2.17 on 2026-09-01 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_cashentry_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expensecategory',
            options={'ordering': ['name']},
        ),
    ]
