# Generated by Django 5.2.17 on 2026-09-14 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_convert_legacy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashentry',
            name='category',
        ),
        migrations.RemoveField(
            model_name='cashentry',
            name='contract',
        ),
        migrations.DeleteModel(
            name='CostSettings',
        ),
        migrations.RemoveField(
            model_name='fixedcost',
            name='category',
        ),
        migrations.DeleteModel(
            name='CashEntry',
        ),
        migrations.DeleteModel(
            name='ExpenseCategory',
        ),
        migrations.DeleteModel(
            name='FixedCost',
        ),
    ]
