# Generated by Django 6.0.6 on 2026-07-06 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BOMItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Норма на 1 шт.')),
            ],
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PriceListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=64, unique=True)),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('labor_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Оплата труда на 1 шт.')),
                ('overhead_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Накладные на 1 шт. (аренда и пр.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True)),
                ('qty', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('planned', 'Запланирован'), ('in_progress', 'В работе'), ('done', 'Завершён'), ('cancelled', 'Отменён')], default='planned', max_length=20)),
                ('materials_written_off', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductionStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('cutting', 'Кесу (крой)'), ('sewing', 'Тігу (пошив)'), ('finishing', 'Әрлеу (отделка)'), ('qc', 'Бақылау (ОТК)'), ('warehouse', 'Қоймаға өткізу')], max_length=20)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('norm_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('actual_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('in_progress', 'В работе'), ('done', 'Готово')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['order', 'position'],
            },
        ),
    ]
