# Generated by Django 6.0.6 on 2026-07-06 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
        ('production', '0001_initial'),
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bomitem',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.material'),
        ),
        migrations.AddField(
            model_name='pricelist',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Пусто = общий прайс', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_lists', to='contracts.customer'),
        ),
        migrations.AddField(
            model_name='pricelistitem',
            name='price_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='production.pricelist'),
        ),
        migrations.AddField(
            model_name='pricelistitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.product'),
        ),
        migrations.AddField(
            model_name='bomitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_items', to='production.product'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_orders', to='contracts.contract'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.product'),
        ),
        migrations.AddField(
            model_name='productionstage',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productionstage',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='production.productionorder'),
        ),
        migrations.AlterUniqueTogether(
            name='pricelistitem',
            unique_together={('price_list', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='bomitem',
            unique_together={('product', 'material')},
        ),
        migrations.AlterUniqueTogether(
            name='productionstage',
            unique_together={('order', 'stage')},
        ),
    ]
