# Generated by Django 6.0.7 on 2026-07-23 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionstage',
            name='stage',
            field=models.CharField(choices=[('cutting', 'Крой'), ('sewing', 'Пошив'), ('finishing', 'Отделка'), ('qc', 'Контроль (ОТК)'), ('warehouse', 'Сдача на склад')], max_length=20),
        ),
    ]
