# Generated by Django 6.0.7 on 2026-08-13 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_alter_productionstage_stage'),
    ]

    operations = [
        migrations.CreateModel(
            name='StageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=32, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Название этапа')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('default_norm_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Норма часов по умолчанию')),
                ('is_active', models.BooleanField(default=True, verbose_name='Использовать в новых заказах')),
            ],
            options={
                'verbose_name': 'Этап производства',
                'verbose_name_plural': 'Этапы производства (конструктор)',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='norm_hours',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Для распределения накладных по нормо-часам', max_digits=8, verbose_name='Норма времени на 1 шт., ч'),
        ),
        migrations.AddField(
            model_name='product',
            name='overhead_override',
            field=models.BooleanField(default=False, help_text='По умолчанию накладные считаются автоматически из постоянных расходов', verbose_name='Задать накладные вручную'),
        ),
        migrations.AddField(
            model_name='productionstage',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название этапа'),
        ),
        migrations.AlterField(
            model_name='product',
            name='labor_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Оплата труда на 1 шт. (переменный)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='overhead_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Используется только если включено переопределение', max_digits=12, verbose_name='Накладные на 1 шт. (ручное значение)'),
        ),
        migrations.AlterField(
            model_name='productionstage',
            name='stage',
            field=models.CharField(max_length=32, verbose_name='Код этапа'),
        ),
    ]
