# Generated by Django 5.2.17 on 2026-08-27 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_stagetemplate_product_norm_hours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRouteStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('norm_hours', models.DecimalField(decimal_places=2, default=0, help_text='0 — взять норму из справочника этапов', max_digits=8, verbose_name='Норма часов на этап')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route', to='production.product')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='in_routes', to='production.stagetemplate', verbose_name='Этап')),
            ],
            options={
                'verbose_name': 'Этап маршрута изделия',
                'verbose_name_plural': 'Маршрут изделия',
                'ordering': ['position', 'id'],
                'unique_together': {('product', 'template')},
            },
        ),
    ]
