# Generated by Django 5.2.17 on 2026-09-01 03:44

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_productroutestage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bomitem',
            name='qty',
            field=models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Норма на 1 шт.'),
        ),
        migrations.AlterField(
            model_name='pricelistitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='product',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='product',
            name='labor_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Оплата труда на 1 шт. (переменный)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='norm_hours',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Для распределения накладных по нормо-часам', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Норма времени на 1 шт., ч'),
        ),
        migrations.AlterField(
            model_name='product',
            name='overhead_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Используется только если включено переопределение', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Накладные на 1 шт. (ручное значение)'),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='qty',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='productroutestage',
            name='norm_hours',
            field=models.DecimalField(decimal_places=2, default=0, help_text='0 — взять норму из справочника этапов', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Норма часов на этап'),
        ),
        migrations.AlterField(
            model_name='stagetemplate',
            name='default_norm_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Норма часов по умолчанию'),
        ),
    ]
