# Generated by Django 5.2.17 on 2026-09-01 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_alter_bomitem_qty_alter_pricelistitem_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bomitem',
            options={'ordering': ['material__name']},
        ),
        migrations.AlterModelOptions(
            name='pricelist',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='pricelistitem',
            options={'ordering': ['product__name']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
    ]
